### PR TITLE
Move game/restart to be generated from a dist file.

### LINKED ISSUE #928: 'restart' should be generated by 'make update'
```
The "restart" script should be generated by "make update" (or something) from 
another file. And when I say "generated" I really just mean "copied". Because 
it's meant to be modified by the user (to set LANG, change the GAMEDIR, etc), 
and it's annoying when it comes up in 'svn diff'.
```

Original issue reported on code.google.com by `mike@keyboardzombie.com` on 8 Mar 2014 at 12:57

### PR DESCRIPTION
**Pull request by tkrajcar**
Closes #928 (good idea, @talvo!!)

For games that are running on a git checkout, that have customized their `game/restart`, pulling to this change will result in a conflict message that might be somewhat confusing for git novices, since git will cowardly refuse to delete their file with local changes. I'm not sure of a good way around that, other than just being ready to answer people's questions when they come asking :) Open to ideas.

### CODE REVIEW

**Comment by talvo** [comment]
I would suggest having this done as part of 'make update' (which also copies the *cnf.dst files to *.cnf, among other things) instead of 'make all'. Also some minor doc tweaks required in places that mention 'make update', then.

**Comment by tkrajcar** [comment]
@talvo Good thoughts, updated the branch. I also removed the bit in INSTALL about doing what `make update` does by hand, since it's  not really a thing anymore.

**Comment by tkrajcar** [comment]
Shouldn't be any make syntax issues here, since I cribbed from other rules that are working :)

**Comment by tkrajcar** [comment]
@talvo :white_check_mark:  ?

**Pull request merged**
