### PR TITLE
Websock

### PR DESCRIPTION
**Pull request by grapenut**
Adds web socket connections to PennMUSH. Connect with a simple javascript client, e.g. http://grapenut.org/code/wsclient/

-grapenut

### CODE REVIEW

**Comment by grapenut** [comment]
I guess the initial pull request was light on background so here is a bit more information on the architecture. 

Websocket connections are initiated when the client sends an HTTP GET request at the login screen:
GET /wsclient HTTP/1.1

Websocket packets are framed which is why we can't just use them natively. Since we have to frame the data anyway it was convenient to use channels to move different types of data, mainly to separate plain text (in which HTML would not be rendered) from HTML code that is supposed to be rendered (i.e. Pueblo). There are also channels defined for binary and JSON data that are not actually used for anything, but are made available to ease bi-directional communication of non-text data (e.g. updating coordinates on a map, HUDs for health/mana, etc.). It is up to the client whether or not they read data on these alternate channels, only plain text and HTML are implemented in the example client.

Aside from adding the basic websocket connections, this pull request also contains a couple of helper functions along the lines of HTML() and TAG*() (for which I just realized I do not have help files). These functions are for sending data on a specific channel, other than the default text channel. They take the form WS?(text to send to websocket clients, text to send to non-websocket clients). WSB() sends binary data types, WSJ() sends JSON objects, and WSH() sends HTML code to be rendered (similar to HTML() but for websockets instead of Pueblo). We may not want WSB() and WSJ() activated by default for the sake of namespace clutter. We may also want to roll WSH() into HTML() for the same reason. These helper functions require the pueblo power (via Can_Pueblo_Send() macro), but you may want them to be wizard only. There is currently no integration with the pueblo support functions but it should in principle be possible.

**Comment by grapenut** [comment]
Made a minor change in order to enable xterm256 color support. Also updated the example client to implement the same.

**Comment by grapenut** [comment]
As a happy addendum, SSL connections are supported natively. The client must use the wss:// protocol (example client updated). You must have ssl_ca_file commented out in mush.cnf to allow SSL connections over HTTPS from Chrome (SSL on HTTP works without it), but since we don't do client authorization anyway it should probably already be commented out. SSL on Safari and Firefox works over HTTP and HTTPS.

**Comment by HarryCordewener** [comment]
I can't seem to get this to work on a clean install using your websocket branch.
On a connection, I get the following error using wsclient:

```WebSocket connection to 'ws://twilightdays.org:4201/wsclient' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED  ``` (It gives a 200 error)

The port is open and I can connect to it using MUSHclient.

**Comment by shawnw** [comment]
And merged.

**Pull request merged**
